pageinfo = [[1106175535,3349],
	[1106176531,3354],
	[1106175795,3357],
	[1106175517,3331],
	[1106175545,3389],
	[1106175805,3398],
	[1106176511,3338],
	[1106176539,3395],
	[1106175779,3341],
	[1106610353,10817],
	[1106604795,3380],
	[1106603803,2830],
	[1106175461,4825],
	[1106175243,4849],
	[1193075807,4597],
	[1193076033,4623],
	[1193076019,4633],
	[1106175569,2712],
	[1106176569,2410],
	[1106175827,2719],
	[1106610479,4784],
	[1106175579,2649],
	[1106176585,2234],
	[1106175837,2651],
	[1106175571,2711],
	[1106176573,2410],
	[1106175831,2720],
	[1177456103,2413],
	[1177456121,2420],
	[1177456155,2418],
	[1106175559,2725],
	[1106176553,2423],
	[1106175819,2734],
	[1106175563,2998],
	[1106175823,2945],
	[1106175551,3484],
	[1106176545,3184],
	[1106175811,3494],
	[1106175547,3493],
	[1106176541,3193],
	[1106175807,3504],
	[1142550563,4213],
	[1142548107,4300],
	[1106176567,2942],
	[1177455401,2783],
	[1177455483,2482],
	[1177455437,2792],
	[1106610383,5398],
	[1106175453,2503],
	[1122049637,3552],
	[1142546241,3963],
	[1106176445,3962],
	[1106175417,3041],
	[1155927709,3236],
	[1106001697,2238],
	[1106002983,6861],
	[1122052847,3992],
	[1142546661,5352],
	[1106002983,6160],
	[1106002983,6867],
	[1107019071,5318],
	[1107019219,4638],
	[1204213129,33454],
	[1105980433,2295],
	[1131040235,13149],
	[1106611103,3242],
	[1106002237,2424],
	[1106175495,18369],
	[1122052823,13166],
	[1142551085,15176],
	[1106176481,18838],
	[1106175751,18608],
	[1106602265,2713],
	[1106590247,2676],
	[1106589031,2920],
	[1106589187,2675],
	[1106175717,3386],
	[1122049187,4489],
	[1122051959,3453],
	[1142551205,2670],
	[1106602793,2811],
	[1142546339,3890],
	[1142546347,3897],
	[1106003315,2337],
	[1106610695,12708],
	[1122050355,2536],
	[1142546403,2281],
	[1106175481,2218],
	[1106176463,2272],
	[1106175251,2226],
	[1106175575,2851],
	[1106176581,2442],
	[1106175835,2866],
	[1122049389,1897],
	[1122052077,1981],
	[1128529445,3825],
	[1128529437,3849],
	[1128529473,3846],
	[1128529687,3661],
	[1128529665,3592],
	[1128529641,3540],
	[1106175513,3132],
	[1106176507,2671],
	[1106175775,3141],
	[1106611173,4303],
	[1106176503,4224],
	[1106175769,4393],
	[1106175587,3158],
	[1106176587,2408],
	[1106175843,3096],
	[1106175599,3046],
	[1106176591,2403],
	[1106175857,3048],
	[1106610435,2977],
	[1106602619,10974],
	[1201535777,50757],
	[1129045409,4091],
	[1106176449,2494],
	[1106175457,2502],
	[1106175239,2513],
	[1106176491,2656],
	[1106175501,2675],
	[1106175761,2681],
	[1106176495,2571],
	[1106175503,2573],
	[1106175763,2579],
	[1107019145,3655],
	[1122050175,4231],
	[1122050057,4173],
	[1177455569,4256],
	[1106175531,2441],
	[1106176527,2489],
	[1106175793,2449],
	[1106175525,3351],
	[1106176517,3117],
	[1106175785,3427],
	[1106175521,3347],
	[1106176515,3128],
	[1106175781,3438],
	[1142546995,3922],
	[1142546965,3909],
	[1106175541,2978],
	[1106176535,2983],
	[1106175799,2985],
	[1177455385,2747],
	[1177455497,2446],
	[1177455545,2756],
	[1223022922,3423],
	[1138818777,5405],
	[1142546289,5412]];
pagedata = [ ["./appendingfiles.html","Appending files","Appending files You can append data to a remote file using any of the Ftp#upload methods that take a second boolean argument. Rather than replace ...",""],
["./appendingfiles2.html","Appending files","Appending files You can append data to a remote file using any of the Sftp#upload methods that take a second boolean argument. Rather than replace...",""],
["./appendingfiles_2.html","Appending files","Appending files You can append data to a remote file using any of the Ftps#upload methods that take a second boolean argument. Rather than replace...",""],
["./automaticallydetectingthetr.html","Automatically detecting the transfer mode","Automatically detecting the transfer mode When uploading files the transfer mode is by default set to binary. Using the Ftp#setAuto method you may...",""],
["./automaticallydetectingthetr2.html","Automatically detecting the transfer mode","Automatically detecting the transfer mode When downloading files the transfer mode is by default set to binary. Using the Ftp#setAuto method you m...",""],
["./automaticallydetectingthetr2_2.html","Automatically detecting the transfer mode","Automatically detecting the transfer mode When downloading files the transfer mode is by default set to binary. Using the Ftps#setAuto method you ...",""],
["./automaticallydetectingthetr3.html","Automatically detecting the transfer mode","Automatically detecting the transfer mode When uploading files the transfer mode is by default set to binary. Using the Sftp#setAuto method you ma...",""],
["./automaticallydetectingthetr4.html","Automatically detecting the transfer mode","Automatically detecting the transfer mode When downloading files the transfer mode is by default set to binary. Using the Sftp#setAuto method you ...",""],
["./automaticallydetectingthetr_2.html","Automatically detecting the transfer mode","Automatically detecting the transfer mode When uploading files the transfer mode is by default set to binary. Using the Ftps#setAuto method you ma...",""],
["./commandlineoptions.html","Command line options","Command line options The following options may be used at the command line when invoking File Transfer Command Line. -h &#60;hostname&#62; Specified the h...",""],
["./commandlineusage.html","Command line usage","Command line usage Usage EXE: ftcl -f scriptfile [-options] Usage JAR: java -jar ftcl.jar -f scriptfile [-options] Example Usage EXE ftcl -f ftpsc...",""],
["./commentsinscriptfiles.html","Comments in script files","Comments in script files The syntax for comments in FTCL script files follows that of the Java programming language. Any text within comments is i...",""],
["./connectingfrombehindafirew.html","Connecting from behind a firewall","Connecting from behind a firewall The Ftp class is firewall friendly in that by default it uses a firewall friendly passive connection. Some firew...",""],
["./connectingfrombehindafirewftps.html","Connecting from behind a firewall","Connecting from behind a firewall The Ftps component is firewall friendly in that by default it uses a firewall friendly passive connection. Some ...",""],
["./connectingthruaproxyserver.html","Connecting thru a proxy server","Connecting thru a proxy server The Ftp class allows for connections through HTTP and SOCKS5 proxy servers. To use a proxy server invoke the Ftp#se...",""],
["./connectingthruaproxyserver2.html","Connecting thru a proxy server","Connecting thru a proxy server The Sftp component allows for connections through HTTP and SOCKS5 proxy servers. To use a proxy server invoke the S...",""],
["./connectingthruaproxyserverftps.html","Connecting thru a proxy server","Connecting thru a proxy server The Ftps component allows for connections through HTTP and SOCKS5 proxy servers. To use a proxy server invoke the F...",""],
["./creatingaremotedirectory.html","Creating a remote directory","Creating a remote directory You can create a remote directory on the server using the Ftp#makeDir method. The directory created is relative to you...",""],
["./creatingaremotedirectory2.html","Creating a remote directory","Creating a remote directory You can create a remote directory on the server using the Sftp#makeDir method. The directory created is relative to yo...",""],
["./creatingaremotedirectory_2.html","Creating a remote directory","Creating a remote directory You can create a remote directory on the server using the Ftps#makeDir method. The directory created is relative to yo...",""],
["./definingandusingvariables.html","Defining and using variables","Defining and using variables Variables may be defined in FTCL at the command line or in a valid FTCL script file. Once a variable is defined it is...",""],
["./deletingafile.html","Deleting a file","Deleting a file You can delete a file using the Ftp#deleteFile method. All filenames are relative to your current remote directory. Example // del...",""],
["./deletingafile2.html","Deleting a file","Deleting a file You can delete a file using the Sftp#deleteFile method. Example // delete file named image.gif sftp.deleteFile(\"image.gif\"); ",""],
["./deletingafile_2.html","Deleting a file","Deleting a file You can delete a file using the Ftps#deleteFile method. All filenames are relative to your current remote directory. Example // de...",""],
["./deletingaremotedirectory.html","Deleting a remote directory","Deleting a remote directory You can delete a remote directory on the server using the Ftp#deleteDir method. The directory deleted is relative to y...",""],
["./deletingaremotedirectory2.html","Deleting a remote directory","Deleting a remote directory You can delete a remote directory on the server using the Sftp#deleteDir method. The directory deleted is relative to ...",""],
["./deletingaremotedirectory_2.html","Deleting a remote directory","Deleting a remote directory You can delete a remote directory on the server using the Ftps#deleteDir method. The directory deleted is relative to ...",""],
["./deletingmultiplefiles.html","Deleting multiple files","Deleting multiple files You can delete multiple files using the Ftp#mdelete method and a regular expression. All files will be deleted from your c...",""],
["./deletingmultiplefiles2.html","Deleting multiple files","Deleting multiple files You can delete multiple files using the Ftps#mdelete method and a regular expression. All files will be deleted from your ...",""],
["./deletingmultiplefiles3.html","Deleting multiple files","Deleting multiple files You can delete multiple files using the Sftp#mdelete method and a regular expression. All files will be deleted from your ...",""],
["./downloadingadirectory.html","Downloading a directory","Downloading a directory You can download an entire directory using the Ftp#downloadDir method and a directory name. Directory to download is relat...",""],
["./downloadingadirectory2.html","Downloading a directory","Downloading a directory You can download an entire directory using the Sftp#downloadDir method and a directory name. Directory to download is rela...",""],
["./downloadingadirectory_2.html","Downloading a directory","Downloading a directory You can download an entire directory using the Ftps#downloadDir method and a directory name. Directory to download is rela...",""],
["./downloadingafiletomemory.html","Downloading files to memory","Downloading files to memory You can download a file and store it to memory by using the Ftp#download method that takes a java.io.OutputStream as i...",""],
["./downloadingafiletomemory_2.html","Downloading files to memory","Downloading files to memory You can download a file and store it to memory by using the Ftps#download method that takes a java.io.OutputStream as ...",""],
["./downloadingasciitextfiles.html","Downloading ASCII text files","Downloading ASCII text files To download ASCII text files you must set the transfer mode to ASCII using the Ftp#setAscii method. All files will be...",""],
["./downloadingasciitextfiles2.html","Downloading ASCII text files","Downloading ASCII text files To download ASCII text files you must set the transfer mode to ASCII using the Sftp#setAscii method. All files will b...",""],
["./downloadingasciitextfiles_2.html","Downloading ASCII text files","Downloading ASCII text files To download ASCII text files you must set the transfer mode to ASCII using the Ftps#setAscii method. All files will b...",""],
["./downloadingbinaryfiles.html","Downloading binary files","Downloading binary files To download binary files you must set the transfer mode to binary (the default) using the Ftp#setBinary method. All files...",""],
["./downloadingbinaryfiles2.html","Downloading binary files","Downloading binary files To download binary files you must set the transfer mode to binary (the default) using the Sftp#setBinary method. All file...",""],
["./downloadingbinaryfiles_2.html","Downloading binary files","Downloading binary files To download binary files you must set the transfer mode to binary (the default) using the Ftps#setBinary method. All file...",""],
["./downloadingdirectories.html","Downloading directories","Downloading directories To download a directory the Scp#downloadDir method. Example // set local directory File localDir = new File(\"C:/tmp\"); scp...",""],
["./downloadingfiles.html","Downloading files","Downloading files To download a file use one of the available Scp#download methods. Example // set local directory File localDir = new File(\"C:/tm...",""],
["./downloadingfilestomemory.html","Downloading files to memory","Downloading files to memory You can download a file and store it to memory by using the Sftp#download method that takes a java.io.OutputStream as ...",""],
["./downloadingmultiplefiles.html","Downloading multiple files","Downloading multiple files You can download multiple files using the Ftp#mdownload method along with a regular expression. All files will be downl...",""],
["./downloadingmultiplefiles2.html","Downloading multiple files","Downloading multiple files You can download multiple files using the Sftp#mdownload method along with a regular expression. All files will be down...",""],
["./downloadingmultiplefiles_2.html","Downloading multiple files","Downloading multiple files You can download multiple files using the Ftps#mdownload method along with a regular expression. All files will be down...",""],
["./escapecharacters.html","Escape characters","Escape characters The FTCL language allows for the use of escape characters when defining strings in the same way that the Java programming langua...",""],
["./establishingaconnection.html","Establishing a connection","Establishing a connection To establish a connection to an FTP server, create an Ftp instance providing the required hostname, username and passwor...",""],
["./establishingaconnection2.html","Establishing a connection","Establishing a connection In order to begin a FXP session you must first create two Ftp instances, one representing the source server and another ...",""],
["./establishingaconnection3.html","Establishing a connection","Establishing a connection To establish a connection create a com.jscape.inet.ssh.util.SshParameters instance providing hostname, username and pass...",""],
["./establishingaconnection5.html","Establishing a connection","Establishing a connection To establish a connection create a com.jscape.inet.ssh.util.SshParameters instance providing hostname, username and pass...",""],
["./establishingaconnectionusin.html","Establishing a connection using Implicit SSL","Establishing a connection using Implicit SSL To establish a connection to an FTP server using Implicit SSL first create an Ftps instance providing...",""],
["./establishingaconnection_2.html","Establishing a connection using Explicit SSL","Establishing a connection using Explicit SSL To establish a connection to an FTP server using Explict SSL (AUTH TLS or AUTH SSL), create an Ftps i...",""],
["./evaluation.html","Evaluation","Evaluation After installation, Secure FTP Factory has a free 30 day evaluation. After the evaluation period has expired Secure FTP Factory compone...",""],
["./eventtypes.html","Event types","Event types The Ftp class is the source for several FTP related events. All events may be captured by registering your class as a listener by impl...",""],
["./eventtypes2.html","Event types","Event types The Fxp class is the source for several FXP related events. All events may be captured by registering your class as a listener by impl...",""],
["./eventtypes3.html","Event types","Event types The Scp class is the source for several SCP related events. All events may be captured by registering your class as a listener by impl...",""],
["./eventtypes7.html","Event types","Event types The Sftp class is the source for several SFTP related events. All events may be captured by registering your class as a listener by im...",""],
["./eventtypes_2.html","Event types","Event types The Ftps class is the source for several FTP related events. All events may be captured by registering your class as a listener by imp...",""],
["./installingthejce.html","Installing the JCE","Installing the JCE The JCE (Java Cryptography Extension) is a set of optional packages for JDK 1.2.x and JDK 1.3.x that provides classes for encry...",""],
["./installingthejsse.html","Installing the JSSE","Installing the JSSE The JSSE (Java Secure Socket Extension) is a set of optional packages for JDK 1.2.x and JDK 1.3.x that enable secure Internet ...",""],
["./introhistory.html","Version history","Version history The following changes have been incorporated. Version 7.4.3 Feb. 28, 2008 Bug Fix: Fixed issue with handling exceptions in respons...",""],
["./introinstallation.html","Installation","Installation All package runtime code is included in the sftp.jar file which should be made available when running or compiling programs which mak...",""],
["./introlicensing.html","License","License SECURE FTP FACTORY LICENSE STATEMENT AND LIMITED WARRANTY IMPORTANT - READ CAREFULLY This license statement and limited warranty constitut...",""],
["./introoverview.html","Overview","Overview Secure FTP Factory is a set of Java based client components for exchanging data between machines. Including FTP (File Transfer Protocol),...",""],
["./introsupport.html","Technical support","Technical support At JSCAPE we strive to provide useful and timely technical support. If you have any technical support issues regarding Secure FT...",""],
["./listeningforevents.html","Listening for events","Listening for events For an object to listen for events published by the Ftp class the following steps are required: 1. Set object to implement Ft...",""],
["./listeningforevents2.html","Listening for events","Listening for events For an object to listen for events published by the Fxp class the following steps are required: 1. Set object to implement Fx...",""],
["./listeningforevents3.html","Listening for events","Listening for events For an object to listen for events published by the Scp class the following steps are required: 1. Set object to implement Sc...",""],
["./listeningforevents7.html","Listening for events","Listening for events For an object to listen for events published by the Sftp class the following steps are required: 1. Set object to implement S...",""],
["./listeningforevents_2.html","Listening for events","Listening for events For an object to listen for events published by the Ftps component the following steps are required: 1. Set object to impleme...",""],
["./overview.html","Overview","Overview The FTCL (File Transfer Command Line) component provides a scripting language allowing developers to quickly script and automate routine ...",""],
["./overview16.html","Overview","Overview The Sftp class provides an easy to use client application programming interface for transferring files between a client and SSH (Secure S...",""],
["./overview2.html","Overview","Overview The Ftp class provides an easy to use client application programming interface for transferring files between a client and FTP (File Tran...",""],
["./overview3.html","Overview","Overview The Ftps class provides an easy to use programming interface for securely exchanging data with an FTP (File Transfer Protocol) server usi...",""],
["./overview4.html","Overview","Overview To establish a secure connection to an FTP server using SSL you may use the Ftps class. The Ftps class allows for client connections to a...",""],
["./overview5.html","Overview","Overview FXP is an extension to the FTP protocol which allows for server to server transfers without actually acquiring the files yourself. For ex...",""],
["./overview6.html","Overview","Overview The Fxps class is very similar to the Fxp class in functionality with the only difference being that the Fxps class uses secure connectio...",""],
["./overview7.html","Overview","Overview The Scp class provides an easy to use client application programming interface for transferring files between a client and SSH (Secure SH...",""],
["./promptinguserfordata.html","Prompting user for data","Prompting user for data You may prompt the user for data using the prompt or promptmask command. This is useful in cases where your script files r...",""],
["./publickeyauthentication.html","Public key authentication","Public key authentication In addition to username/password authentication, the Scp class supports another authentication method known as public ke...",""],
["./publickeyauthenticationsftp.html","Public key authentication","Public key authentication In addition to username/password authentication, the Sftp class supports another authentication method known as public k...",""],
["./purchase.html","Purchase","Purchase You may securely purchase Secure FTP Factory online using most major credit cards. All software is delivered electronically within 24 hou...",""],
["./relativev_s_absolutepaths.html","Relative v.s. absolute paths","Relative v.s. absolute paths Several commands in the FTCL language make reference to relative and absolute paths. Understanding how relative and a...",""],
["./releasingaconnection.html","Releasing a connection","Releasing a connection To release a connection from the source and destination servers simply invoke the Ftp#disconnect method for each Ftp instan...",""],
["./releasingaconnection2.html","Releasing a connection","Releasing a connection To disconnect from an SSH server, invoke the Scp#disconnect method. You should always disconnect from the SSH server when e...",""],
["./releasingaconnection6.html","Releasing a connection","Releasing a connection To disconnect from an FTP server, invoke the Ftp#disconnect method. You should always disconnect from the FTP server when e...",""],
["./releasingaconnection7.html","Releasing a connection","Releasing a connection To disconnect from an SSH server, invoke the Sftp#disconnect method. You should always disconnect from the SSH server when ...",""],
["./releasingaconnection8.html","Releasing a connection","Releasing a connection To disconnect from an FTP server, invoke the Ftps#disconnect method. You should always disconnect from the FTP server when ...",""],
["./renamingafile.html","Renaming a file","Renaming a file You can rename a file using the Ftp#renameFile method providing the current file name and the new file name. All filenames are rel...",""],
["./renamingafile2.html","Renaming a file","Renaming a file You can rename a file using the Sftp#renameFile method providing the current file name and the new file name. Example // rename fi...",""],
["./renamingafile_2.html","Renaming a file","Renaming a file You can rename a file using the Ftps#renameFile method providing the current file name and the new file name. All filenames are re...",""],
["./requirements.html","Requirements","Requirements In order to transfer data using FXP you must use a server that supports FXP and has FXP enabled. Contact your FTP server vendor and d...",""],
["./requirements2.html","Requirements","Requirements In order to do secure FXP transfers using SSL both source and destination servers must support the FTP extension SSCN (set secured cl...",""],
["./resumingdownloads.html","Resuming downloads","Resuming downloads If a file fails to download completely you can resume the download using any of the Ftp#resumeDownload methods. Prior to using ...",""],
["./resumingdownloads2.html","Resuming downloads","Resuming downloads If a file fails to download completely you can resume the download using any of the Ftps#resumeDownload methods. Prior to using...",""],
["./resumingdownloads3.html","Resuming downloads","Resuming downloads If a file fails to download completely you can resume the download using any of the Sftp#resumeDownload methods. Prior to using...",""],
["./resuminguploads.html","Resuming uploads","Resuming uploads If a file fails to upload completely you can resume the upload using any of the Ftp#resumeUpload methods. Prior to using the Ftp#...",""],
["./resuminguploads2.html","Resuming uploads","Resuming uploads If a file fails to upload completely you can resume the upload using any of the Ftps#resumeUpload methods. Prior to using the Ftp...",""],
["./resuminguploads3.html","Resuming uploads","Resuming uploads If a file fails to upload completely you can resume the upload using any of the Sftp#resumeUpload methods. Prior to using the Sft...",""],
["./retrievingalocaldirectoryl.html","Retrieving a local directory listing","Retrieving a local directory listing To get a local directory listing of your current local directory use the Ftp#getLocalDirListing method. This ...",""],
["./retrievingalocaldirectoryl2.html","Retrieving a local directory listing","Retrieving a local directory listing To get a local directory listing of your current local directory use the Sftp#getLocalDirListing method. This...",""],
["./retrievingalocaldirectoryl_2.html","Retrieving a local directory listing","Retrieving a local directory listing To get a local directory listing of your current local directory use the Ftps#getLocalDirListing method. This...",""],
["./retrievingaremotedirectory.html","Retrieving a remote directory listing","Retrieving a remote directory listing Getting a directory listing as a String To get a directory listing returned as a string you may use the Ftp#...",""],
["./retrievingaremotedirectory2.html","Retrieving a remote directory listing","Retrieving a remote directory listing There are two ways that you can retrieve a directory listing from the server. The method used will depend on...",""],
["./retrievingaremotedirectory_2.html","Retrieving a remote directory listing","Retrieving a remote directory listing Getting a directory listing as a String To get a directory listing returned as a string you may use the Ftps...",""],
["./retrievingfilesizeinformatio.html","Retrieving filesize information","Retrieving filesize information You can retrieve the byte size of a file using the Ftp#getFilesize method. All filenames are relative to your curr...",""],
["./retrievingfilesizeinformatio2.html","Retrieving filesize information","Retrieving filesize information You can retrieve the byte size of a file using the Sftp#getFilesize method. Example // get size of file image.gif ...",""],
["./retrievingfilesizeinformatio_2.html","Retrieving filesize information","Retrieving filesize information You can retrieve the byte size of a file using the Ftps#getFilesize method. All filenames are relative to your cur...",""],
["./retrievingfiletimestampinfo.html","Retrieving file timestamp information","Retrieving file timestamp information You can retrieve the date a file was last modified using the Ftp#getFileTimestamp method. All filenames are ...",""],
["./retrievingfiletimestampinfo2.html","Retrieving file timestamp information","Retrieving file timestamp information You can retrieve the date a file was last modified using the Sftp#getFileTimestamp method. Example // get la...",""],
["./retrievingfiletimestampinfo_2.html","Retrieving file timestamp information","Retrieving file timestamp information You can retrieve the date a file was last modified using the Ftps#getFileTimestamp method. All filenames are...",""],
["./runningftclscriptsfromwith.html","Running FTCL scripts from within Ant","Running FTCL scripts from within Ant Apache Ant is a Java based build tool that is used for automating software builds. File Transfer Command Line...",""],
["./runningftclscriptsfromwith2.html","Running FTCL scripts from within Java","Running FTCL scripts from within Java FTCL scripts may be processed from within Java code by creating a new FTCL instance and invoking the appropr...",""],
["./scriptingcommands.html","Scripting commands","Scripting commands The following commands may be used in a script file when invoking File Transfer Command Line. append cd connect del deldir disc...",""],
["./settingclientandservercert.html","Setting client and server certificates","Setting client and server certificates When establishing a connection you may define any optional client certificates that should be used for auth...",""],
["./settingconnectiontimeout5.html","Setting connection timeout","Setting connection timeout You can use the Sftp#setTimeout method to define the maximum number of milliseconds to wait when establishing a connect...",""],
["./settingnetworkconnectiontim.html","Setting connection timeout","Setting connection timeout You can use the Ftp#setTimeout method to define the maximum number of milli-seconds to wait when establishing a connect...",""],
["./settingnetworkconnectiontim_2.html","Setting connection timeout","Setting connection timeout You can use the Ftps#setTimeout method to define the maximum number of milli-seconds to wait when establishing a connec...",""],
["./settingyourlocaldirectory2.html","Setting your local directory","Setting your local directory Your local directory is the relative path from which all files will be uploaded from or downloaded to when communicat...",""],
["./settingyourlocaldirectoryftp.html","Setting your local directory","Setting your local directory Your local directory is the relative path from which all files will be uploaded from or downloaded to when communicat...",""],
["./settingyourlocaldirectoryftps.html","Setting your local directory","Setting your local directory Your local directory is the relative path from which all files will be uploaded from or downloaded to when communicat...",""],
["./settingyourremotedirectory2.html","Setting your remote directory","Setting your remote directory Your remote directory is the directory on the server from which all files will be uploaded to or downloaded from whe...",""],
["./settingyourremotedirectoryftp.html","Setting your remote directory","Setting your remote directory Your remote directory is the directory on the server from which all files will be uploaded to or downloaded from whe...",""],
["./settingyourremotedirectoryftps.html","Setting your remote directory","Setting your remote directory Your remote directory is the directory on the server from which all files will be uploaded to or downloaded from whe...",""],
["./systemrequirements.html","System requirements","System requirements JDK requirements JDK 1.2.2 or greater You may download the latest JDK at http://java.sun.com Platform requirements Secure FTP ...",""],
["./transferringadirectory.html","Transferring a directory","Transferring a directory Once you have established a connection to the source and destination FTP servers you may transfer an entire directory rec...",""],
["./transferringafile.html","Transferring a file","Transferring a file Once you have established a connection to the source and destination FTP servers you may transfer a file using the Fxp#transfe...",""],
["./transferringmultiplefiles.html","Transferring multiple files","Transferring multiple files Once you have established a connection to the source and destination FTP servers you may transfer multiple files match...",""],
["./uploadingadirectory.html","Uploading a directory","Uploading a directory You can upload an entire directory using the Ftp#uploadDir method and a File representing a directory on your local system. ...",""],
["./uploadingadirectory2.html","Uploading a directory","Uploading a directory You can upload an entire directory using the Sftp#uploadDir method and a java.io.File representing a directory on your local...",""],
["./uploadingadirectory_2.html","Uploading a directory","Uploading a directory You can upload an entire directory using the Ftps#uploadDir method and a File representing a directory on your local system....",""],
["./uploadingasciitextfiles.html","Uploading ASCII text files","Uploading ASCII text files To upload ASCII text files you must set the transfer mode to ASCII using the Ftp#setAscii method. All files with relati...",""],
["./uploadingasciitextfiles2.html","Uploading ASCII text files","Uploading ASCII text files To upload ASCII text files you must set the transfer mode to ASCII using the Sftp#setAscii method. All files with relat...",""],
["./uploadingasciitextfiles_2.html","Uploading ASCII text files","Uploading ASCII text files To upload ASCII text files you must set the transfer mode to ASCII using the Ftps#setAscii method. All files with relat...",""],
["./uploadingbinaryfiles.html","Uploading binary files","Uploading binary files To upload binary files you must set the transfer mode to binary (the default) using the Ftp#setBinary method. All files wit...",""],
["./uploadingbinaryfiles2.html","Uploading binary files","Uploading binary files To upload binary files you must set the transfer mode to binary (the default) using the Sftp#setBinary method. All files wi...",""],
["./uploadingbinaryfiles_2.html","Uploading binary files","Uploading binary files To upload binary files you must set the transfer mode to binary (the default) using the Ftps#setBinary method. All files wi...",""],
["./uploadingdirectories.html","Uploading directories","Uploading directories To upload a directory use one of the available Scp#uploadDir methods. Example // local directory to upload File dir = new Fi...",""],
["./uploadingfiles.html","Uploading files","Uploading files To upload a file use one of the many Scp#upload methods. Example // local file to upload File file = new File(\"c:/tmp/file.txt\"); ...",""],
["./uploadingfilesfrommemory.html","Uploading files from memory","Uploading files from memory You can upload data from memory using any of the Ftp#upload methods that take a byte array as it&#39;s first argument. Exa...",""],
["./uploadingfilesfrommemory2.html","Uploading files from memory","Uploading files from memory You can upload data from memory using any of the Sftp#upload methods that take a byte array as it&#39;s first argument. Ex...",""],
["./uploadingfilesfrommemory_2.html","Uploading files from memory","Uploading files from memory You can upload data from memory using any of the Ftps#upload methods that take a byte array as it&#39;s first argument. Ex...",""],
["./uploadingmultiplefiles.html","Uploading multiple files","Uploading multiple files You can upload multiple files using the Ftp#mupload method and a regular expression. All files will be uploaded from your...",""],
["./uploadingmultiplefiles2.html","Uploading multiple files","Uploading multiple files You can upload multiple files using the Sftp#mupload method and a regular expression. All files will be uploaded from you...",""],
["./uploadingmultiplefiles_2.html","Uploading multiple files","Uploading multiple files You can upload multiple files using the Ftps#mupload method and a regular expression. All files will be uploaded from you...",""],
["./userguide_ftsearch.html","Secure FTP Factory User Guide","Secure FTP Factory User Guide Contents &#166; Index &#166; Search Enter one or more keywords to search (&#39;*&#39; and &#39;?&#39; wildcards are supported): You must have ...",""],
["./validatinghostkeys.html","Validating host keys","Validating host keys When connecting to an SSH server using the Sftp class you may define that your login credentials only be submitted to hosts t...",""],
["./validatinghostkeys2.html","Validating host keys","Validating host keys When connecting to an SSH server using the Scp class you may define that your login credentials only be submitted to hosts th...",""]];
